import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import './globals.css'
import Navbar from './components/Navbar/Navbar'
import Sidebar from './components/Sidebar/Sidebar'
import SessionProvider from "./components/SessionProvider/SessionProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Case Browser',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();

  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Navbar />
          <div className="flex overflow-clip pt-[4.25rem] h-screen">
            <Sidebar />
            <div className="p-2 overflow-scroll w-full">
              {children}
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
