import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import './globals.css'
import Navbar from './components/Navbar/Navbar'
import SessionProvider from "./components/SessionProvider/SessionProvider";
import { authOptions } from './api/auth/[...nextauth]/authOptions'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Case Browser',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <SessionProvider session={session} refetchOnWindowFocus refetchInterval={60}>
          <Navbar />
          <div className="flex overflow-clip pt-[3.5rem] h-screen">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
